name: Build Obelisk API

on:
  push:
    branches:
      - "development"
    paths:
      - "obelisk-api"
  pull_request:
    branches:
      - "development"
    paths:
      - "obelisk-api"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file obelisk-api/pom.xml